on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: fix git
      shell: bash -l {0}
      run: |
        git config --global --add safe.directory /github/workspace
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v3
